export const DEFAULT = 'DEFAULT';

//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_RETRY = 'LOGIN_RETRY';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';

//
export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_RESPONSE = 'CUSTOMER_DETAILS_RESPONSE';
export const CUSTOMER_DETAILS_UPDATE = 'CUSTOMER_DETAILS_UPDATE';

// Product list
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_RESPONSE = 'PRODUCT_LIST_RESPONSE';

//Product Details
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_RESPONSE = 'PRODUCT_DETAILS_RESPONSE';

//Order List
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_RESPONSE = 'ORDER_LIST_RESPONSE';
export const ORDER_LIST_DELETE = 'ORDER_LIST_DELETE';
export const ORDER_LIST_ADD = 'ORDER_LIST_ADD';
export const ORDER_LIST_UPDATE = 'ORDER_LIST_UPDATE';
